// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:94b64cad-0659-465f-9a12-8e8ac597ad4c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vOg4HSZc8",
    "aws_user_pools_web_client_id": "7vgc5gd7q20k1p4m8ar9bcqd8m",
    "oauth": {},
    "recorder" : {
      "enable": false,
    },
    "aws_cloud_logic_custom": [
        {
            "name": "api9819f38d",
            "endpoint": "https://ku6y30qtm8.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "eps-serverless-20190630232834-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1dwxwawmw0ih7.cloudfront.net",
    "aws_user_files_s3_bucket": "eps-serverlessc5940ff4146a4cbc86df2d32b803996c-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
